### ISSUE TITLE
building_rotation_angles

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-description-schema#103]
I don't think we need RulesetModelInstance.building_rotation_angles because each instance will correspond to particular orientation that will be evident based on sufrace.azimuth

**Comment by mkarpman** [comment]
We discussed at the RDS call yesterday that we will be adding "AppG B_RMDs Equals" field to all RMD attributes. (Is there a way to do it automatically?) It would be true for the attributes that must match, and false for those that must or may differ (azimuths, HVAC capacities, etc.). The equivalency will then be verified using an umbrella check.  

We also discussed that after RCT parses the RMDs it will identify the B-RMD that has azimuths that match P-RMD and apply all RDSs applicable to B-RMD that were developed thus far to this main B-RMD. There would be a new RDS to verify that azimuths of the other three B-RDSs differ by 90. 180 and 270 compared to the P-RMR. We would also apply a subset of existing RDSs to these other three RDSs - e.g., to confirm that system efficiencies are established correctly for the modified capacity.  

With this approach, RCT will not use the building_rotation_angle field even if it is included in the RMD. @supriyagoel please confirm my understanding of what we discussed.

**Comment by supriyagoel** [comment]
yes, this is what was discussed. Though I'm wondering if things could be made  simpler by just verifying the building rotation angle instead of verifying the azimuth for each surface in the B-RMR

I am also ok with using surfaces azimuth if that makes more sense

**Comment by mkarpman** [comment]
Rotation angle is something a compliance shell would need to generate, but I think we planned to instead rely on direct simulation inputs with all RDSs.

**Comment by JasonGlazer** [comment]
EnergyPlus and I think other software have inputs specifically to rotate entire buildings so I think we should keep it.

And yes, there are some tricks that we can use to add an entirely new field if we want.

**Comment by supriyagoel** [comment]
@JasonGlazer  i believe you're talking about this input? If yes, i agree that it makes sense to have a building level input

<img width="602" alt="image" src="https://user-images.githubusercontent.com/8323384/164314312-9fb36614-def9-4715-8ea7-9819f37f70ea.png">

**Comment by JasonGlazer** [comment]
That's it. I actually programmed that many years ago.

**Comment by mkarpman** [comment]
DOE2 uses a hierarchy of four coordinate systems that are all related to each other by translation and rotation - building coordinates, floor coordinates, space coordinates and wall coordinates. You can rotate the building by changing building coordinates via a parametric run - updating building azimuth effectively updates orientation of all surfaces without actually changing azimuth property of a surface. 
![image](https://user-images.githubusercontent.com/65044990/164320338-9d9fb83e-b74d-485b-a801-9965b5f30351.png)

However, since RMD just includes azimuth for each surface, the nested coordinates would need to be "flattened" so that the surface.azimuth is updated to indicate building rotation. So I am not quite sure how you see this new field working.

**Comment by JasonGlazer** [comment]
I guess equest would need to just flatten the floor, space and wall coordinate systems and not the building rotation. That would be left for RulesetModelInstance.building_rotation_angle in the RMD.

**Comment by mkarpman** [comment]
Building rotation angle may not be zero to begin with, e.g., to position building in a certain way relative to a fixed shade. Also, instead of rotating by changing building azimuth modelers can also be rotated by changing azimuth of each surface via an expression. Either would produce the same surface orientation. We agreed to avoid using ruleset-specific nomenclature in the RMD. Building rotation is a feature of compliance shell and not an inherent model attribute, so why use it?

**Comment by JasonGlazer** [comment]
Addressed in 0.0.16 by not having RulesetModelInstance.building_rotation_angle but including rotation enumerations in RulesetModelType2019ASHRAE901
