### ISSUE TITLE
Add CoolingSystem.full_load_efficiency_no_fan

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-description-schema#106]
We now have CoolingSystem.full_load_efficiency_no_fan, but also need to add this field to HeatingSystem for heat pumps. The relevant App G rule is "The proposed design HVAC system shall be modeled using manufacturers’ full- and partload data for the HVAC system without fan power."

**Comment by JasonGlazer** [comment]
I think this was already present in 0.0.15
