### ISSUE TITLE
Insufficient number of output_validation_points for fans

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-description-schema#109]
Table G3.1.3.15 provides 11 pairs of fan part load ratio / fraction of full load power values for VAV fan systems. In order to fully verify alignment with this table, RMD needs to include the same number of points (11) for the same flow fractions (values in first column of the table - 0, 0.1, etc.) However, currently a note to the output_validation_points says "... A minimum number of four points is recommended." Suggest updating the note to require 11 output validation pairs for App G and specify flow fractions (0, 0.1, etc.)

**Comment by JasonGlazer** [comment]
This seems like a ruleset-specific restriction rather than something we want in the general schema.

**Comment by mkarpman** [comment]
So where should this requirement be added? I think we need it somewhere, because as it stands now RCT will be flagging insufficient validation points.

**Comment by JasonGlazer** [comment]
A good question. If we have a few things like this then I would say we can just describe it textually in a ruleset-specific appendix to 229 but if we have a lot, then maybe we should have a special "schema modification" schema.

**Comment by supriyagoel** [comment]
@mkarpman and @JasonGlazer I agree that this seems to be a ruleset specific requirement but creating a special schema seems to be a lot of work. If the S-WG is open to adding notes for specific rulesets then maybe we could simply have 2 columns, 'Generic Notes' and 'Ruleset Specific Notes'. The Generic Notes could say a minimum of 4 data points are recommended and the ruleset specific notes could say a minimum of 11 points are required for 90.1

**Comment by JasonGlazer** [comment]
In 0.0.17, I added to the note:

> Certain rulesets may have a different minimum number of points. For example, 90.1 Appendix G expects 11 data points.

If we find that we need special ruleset specific notes very often we might want to add the new field that @supriyagoel suggested.
