### ISSUE TITLE
Move several attributes from building level to building segment level

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-description-schema#11]
It seems that the following elements should be moved from building to building segment level: number_of_floors, elevators, refrigeration_components

**Comment by supriyagoel** [comment]
@mkarpman we might still need the number of floors at building level to determine that value for baseline HVAC system- correct? 
Why do we need refrigeration components and elevators at building segment level?

**Comment by mkarpman** [comment]
> @mkarpman we might still need the number of floors at building level to determine that value for baseline HVAC system- correct?

I don't know. For example, if we have mixed use retail/public assembly, wouldn't we need to know number of floors for each occupancy type (i.e. building segment) and not building as a whole?

**Comment by mkarpman** [comment]
> Why do we need refrigeration components and elevators at building segment level?

I wonder if refrigeration should actually be referenced from Space, like lighting and equipment. It contributes to internal heat gains/losses, so may need to be accounted for when determining baseline HVAC systems. Same may apply to elevators. In the model, different schedules may be modeled for elevators that are part of different building segment because segments may have different operating hours. The latter may or may not matter for RMR though.

**Comment by JasonGlazer** [comment]
I believe all the specific issues raised have been already addressed.
