### ISSUE TITLE
Additional Heating_system fields to capture HP performance

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-description-schema#110]
We currently have heating_system.full_load_efficiency_no_fan and heating_system.part_load_efficiency, which do not seem to fit well with HP. I suggest changing heating_system.full_load_efficiency_no_fan to heating_system.full_load_efficiency_47_no_fan (or adding this as a new field) and adding heating_system.full_load_efficiency_17_no_fan, to align with metric in Table G3.5.2 for heating. If we keep  heating_system.full_load_efficiency_no_fan, then perhaps it could be used for PTHP (Table G3.5.4) and unitary heat pumps less than 65 kBtu/hr (Table G3.5.2) which have single rating.

**Comment by JasonGlazer** [comment]
Addressed in 0.0.17
