### ISSUE TITLE
lighting power per area for interior lighting

### ISSUE THREAD

**Issue by weilixu** [open229/ruleset-model-description-schema#112]
https://github.com/open229/ruleset-model-description-schema/blob/master/docs229/ASHRAE229.schema.json#L1153

It seems we only have `power_per_area` for defining lighting power density. 
In Table G3.7, atrium space lighting power is measured by per foot.

OSSTD has a way to convert it into `power_per_area` by estimating the height of the space.
@mkarpman do we need to also include the logic of converting `power per foot height` to `power per area` to make sure the BEM vendor implements it correctly?

**Comment by JasonGlazer** [comment]
@weilixu weirdly those value in G3.7 are in (W/sqft)/ft. I really am not sure it makes sense to have a specific data element for this case. How about we just use Zone.volume/ sum(Space.floor_area) as a surrogate for height?

**Comment by weilixu** [comment]
> @weilixu weirdly those value in G3.7 are in (W/sqft)/ft. I really am not sure it makes sense to have a specific data element for this case. How about we just use Zone.volume/ sum(Space.floor_area) as a surrogate for height?

Sorry for my super delayed reply to this issue. @JasonGlazer suggestion is exactly how we used in the RCT in the past two weeks. We created a ruleset specific function to calculate the average height of a zone by doing `Zone.volume / sum(Space.floor_area)`. Thanks @JasonGlazer @mkarpman for your inputs.
