### ISSUE TITLE
G3.1.3.14 "Supply air temperature setpoint shall be constant at the design condition" requires additional input at terminal level

### ISSUE THREAD

**Issue by supriyagoel** [open229/ruleset-model-description-schema#114]
G3.1.3.12 deals with cooling SAT (control of cooling coil), and G3.1.3.14 is for heating temperature for fan-powered boxes.
This requires an additional input at the terminal level for reheat temperature control with same options as the 'temperature_control' parameter under FanSystems.
Dont think we need terminal.supply_temperature_setpoint- not sure if there are any rules which specify the reheat SAT

**Comment by mkarpman** [comment]
I agree with Supriya.

**Comment by mkarpman** [comment]
For what it's worth, in eQUEST, the relevant keyword is Zone-Fan-T-SCH which is a schedule with the zone temperature at which the terminal blower turns on. Using the enumerations above, that supports CONSTANT (when all schedule setpoints are the same) or SCHEDULED.

**Comment by JasonGlazer** [comment]
@mkarpman ok, I will add back SCHEDULED

**Comment by JasonGlazer** [comment]
This will be part of 0.0.17
