### ISSUE TITLE
Incorrect units on pump_power_per_flow_rate

### ISSUE THREAD

**Issue by jugonzal07** [open229/ruleset-model-description-schema#132]
I believe that, dimensionally, the units are incorrect on this parameter.
https://github.com/open229/ruleset-model-description-schema/blob/master/docs229/ASHRAE229.schema.json#L2862

The units read `W/s-L` but I imagine this was meant to be `W-s/L` perhaps? That would agree dimensionally with a `W/gpm` in IP units.

**Comment by JasonGlazer** [comment]
Thanks @jugonzal07 this will be addressed in the 0.0.21 update
