### ISSUE TITLE
Change HeatingVentilationAirConditioningSystem to HeatingVentilatingAirConditioningSystem

### ISSUE THREAD

**Issue by JasonGlazer** [open229/ruleset-model-description-schema#137]
Change the name of this data group to using "Ventilating" a verb instead of "Ventilation" a noun to be consistent with other verbs being used. 

Suggestion during ballot on "Approval for HeatingVentilationAirConditioningSystem, HeatingSystem, and CoolingSystem" by Matthew Steen.

**Comment by MatthewSteen** [comment]
Thanks. Feel free to just @matthewsteen me too.

**Comment by JasonGlazer** [comment]
Addressed in 0.0.22
