### ISSUE TITLE
in Zone, create transfer_airflow_source_zone

### ISSUE THREAD

**Issue by KarenWGard** [open229/ruleset-model-description-schema#142]
in ASHRAE 90.1 Appendix G3.1.1.e, there is an HVAC system type change in the baseline model for some zones if they are not mechanically cooled in the proposed model.  "Mechanically cooled" is defined as either being supplied directly with cooling, or receiving transfer air from a mechanically cooled zone.

The schema currently includes transfer air, but not the source zone, so it is impossible to determine if the transfer air is coming from a mechanically cooled zone.

I propose to add `transfer_airflow_source_zone` in Zone - this would be a reference (or perhaps an id) of the transfer air source zone.

Thank you

**Comment by JasonGlazer** [comment]
Will be addressed in 0.0.23

**Comment by KarenWGard** [comment]
😁🙏
