### ISSUE TITLE
Supply-air-to-room temperature set-point difference of 20°F for Autosizing

### ISSUE THREAD

**Issue by claperle** [open229/ruleset-model-description-schema#146]
Section G3.1.2.8.1 requires the following:
"For baseline system types 1-8 and 11-13, system design supply airflow rates shall be based on a supply-air-to-room temperature set-point difference of 20°F or the minimum outdoor airflow rate, or the airflow rate required to comply with applicable codes or accreditation standards, whichever is greater. For systems with multiple zone thermostat setpoints, use the design set point that will result in the lowest supply air cooling set point or highest supply air heating set point. "

To assess this we have the following Zone data elements: design_thermostat_cooling_setpoint and design_thermostat_heating_setpoint. We appear to be missing design_supply_air_temperature_heating_setpoint and design_supply_air_temperature_cooling_setpoint at the fan_system and terminal data table levels. We also appear to be missing a data element to indicate that fan cfm has been autosized. 

There were some suggestions for how to integrate this into the schema on our weekly RDS call ranging from the detail above to just adding a boolean data element indicating autosized_with_20F_delta_T.

**Comment by claperle** [comment]
Discussed on call modify Terminal supply_setpoint_temperature to supply_design_heating_setpoint_temperature and add supply_design_cooling_setpoint_temperature. Remove supply_setpoint_temperature from the FanSystem object. Add note to tell software tool vendors that the supply_design_heating_setpoint_temperature and supply_design_cooling_setpoint_temperature should be specified at the Terminal level even for single zone systems.

**Comment by JasonGlazer** [comment]
Addressed in 0.0.24
