### ISSUE TITLE
Equivalency of baseline runs

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-description-schema#149]
In cases when baseline has to be "rotated", there will be four ModelInstances, one for each orientation. Majority of fields would be the same between the four RMDs, and only a handful (e.g., surface azimuths) will differ. To tag the fields that must be the same across the 4 baseline RMD, suggest adding a field "AppG B_RMDs Same="unknown"" to each data element. Ideas for a better label are welcome.

**Comment by JasonGlazer** [comment]
@mkarpman I was looking back at notes about additional tags and see that you wanted to add the one described above and another called "AppG Required"

We currently have:

      RMD Test: "unknown"
      AppG Used By TCDs: "unknown"
      AppG P_RMD Equals U_RMD: "unknown"
      AppG B_RMD Equals P_RMD: "unknown"

but this would adding two:

      RMD Test: "unknown"
      AppG Used By TCDs: "unknown"
      AppG P_RMD Equals U_RMD: "unknown"
      AppG B_RMD Equals P_RMD: "unknown"
      AppG B_RMDs Same="unknown"
      AppG Required = "unknown"

before I add this to YAML file, I just wanted to confirm that we still want these two new fields and that you agree with the names.

**Comment by mkarpman** [comment]
Yes to AppG B_RMDs Same.

I am embarrassed to admit that I don't remember what "AppG Required" is for. Is this for elements that are not checked by the TCDs (AppG Used By TDCs=FALSE) but are addressed in App G?

**Comment by JasonGlazer** [comment]
The only note I have is from a September 22 email referencing a call that it was discussed.  See "Re: HVAC Function and Section 19" If it doesn't ring a bell, we can drop it. Sorry, it has been so long.

**Comment by mkarpman** [comment]
Sounds good. So let's just add "AppG B_RMDs Same: "unknown"" for now. I'll also send email to Weili, Supriya, etc. to see if they remember.

**Comment by JasonGlazer** [comment]
Addressed in pull request #171 that updated to 0.0.27

**Comment by JasonGlazer** [comment]
@mkarpman I added the AppG B_RMDs Same: "unknown" into the main branch and also the "mkarpman-patch-1" branch that you were working on to update all the special tags in the schema file. You should be able to continue your work on that including now setting the AppG B_RMDs Same tag. Let me know if you have any questions.

**Comment by mkarpman** [comment]
Thanks!
