### ISSUE TITLE
Add coincident_unmet_load_hours to schema

### ISSUE THREAD

**Issue by claperle** [open229/ruleset-model-description-schema#151]
To assess the following rules, "Unmet load hours for the proposed design shall not exceed 300 (of the 8760 hours simulated). " and "Unmet load hours for the baseline design shall not exceed 300 (of the 8760 hours simulated). ", we need to have the coincident_unmet_load_hours. In other words, right now we have unmet_load_hours_heating and unmet_load_hours_cooling but if there is an unmet heating and cooling load hour during the same hour then they will be counted twice instead of once so we cannot properly assess these rules unless we have coincident_unmet_load_hours. 

Jason will look into this per call on 12/15. RDS created assuming implementation in the schema, https://github.com/pnnl/ruleset-checking-tool/pull/688

**Comment by JasonGlazer** [comment]
Is addressed in 0.0.24
