### ISSUE TITLE
Notes throughout Schema for where Heating and Cooling Coils should be Specified

### ISSUE THREAD

**Issue by claperle** [open229/ruleset-model-description-schema#158]
I believe we decided (and this is the way the baseline hvac functions perform their checks) that for four pipe fan coil units, etc. the heating and cooling coil would be defined at the terminal. Reading the note shown below from the Terminal.type data element (I have seen this note under HeatingSystem and CoolingSystem as well) it appears that projects are being directed to define them at the HVAC system level via HeatingSystem and CoolingSystem object. I think this should be updated to direct software tool developers to define the coils for the systems are the terminal. 

![image](https://user-images.githubusercontent.com/92933945/210877957-b1d6073f-9dff-4182-a427-daec1b457ff9.png)

**Comment by claperle** [comment]
Proposed language:
System configurations that typically are at the zone and include a compressor (such as packaged terminal air conditioning, packaged terminal heat pumps, window air conditioning units, and water loop heat pumps) should be reported in the schema using HeatingSystem and CoolingSystem. Systems that include gas or electric furnaces should be reported in the schema using HeatingSystem. System configurations that are at the zone and only include fans and coils (such as four-pipe fan coil, two-pipe fan coil, radiant systems, baseboards, and chilled beams) should be reported in the schema using Terminal with the chilled water and hot water systems described in the cooling_source and heating_source data elements (and any other relevant Terminal data elements). Evaporative cooling systems should be described in CoolingSystem. Passive diffusers with no coil or fan should be described in Terminal.

**Comment by JasonGlazer** [comment]
Addressed in #0.025 update
