### ISSUE TITLE
Add note to schema that field may be either simulation input or, if autosized, an output as applicable

### ISSUE THREAD

**Issue by claperle** [open229/ruleset-model-description-schema#166]
Since fans are autosized, we can only get fansystem.minimum_airflow based on simulation outputs. Please add a note to this effect to the schema for data elements that fall into this category (fan cfm, heating and cooling capacities, etc.). It would say that this field may be either simulation input or, if autosized, simulation output.

**Comment by JasonGlazer** [comment]
Addressed in 0.0.26 update
