### ISSUE TITLE
Replace Terminal.Fan with Terminal.SuppyFan 

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-description-schema#167]
It is my understanding that the fan object referenced at the terminal level is always a supply fan. If so, recommend changing Fan to SupplyFan for clarity.

**Comment by JasonGlazer** [comment]
@mkarpman sometimes a fan can be an induction fan like in a parallel fan powered box so it would not be quite right to call that a supply fan.

**Comment by JasonGlazer** [comment]
@mkarpman can I close this issue or do you still want to change the name of Terminal.Fan to something else?
