### ISSUE TITLE
The max Items in the hourly_values does not support leap year

### ISSUE THREAD

**Issue by weilixu** [open229/ruleset-model-description-schema#169]
The RMD supports [leap year](https://github.com/open229/ruleset-model-description-schema/blob/main/docs229/ASHRAE229.schema.json#L1521) in the Calendar object.

However, in the Schedule object, the max items for the `hourly_values` is [8760](https://github.com/open229/ruleset-model-description-schema/blob/main/docs229/ASHRAE229.schema.json#L1441), which means the schedule object does not support leap year schedule.

Could we change the max items to 8784 hours?

**Comment by JasonGlazer** [comment]
Good catch @weilixu!

**Comment by JasonGlazer** [comment]
Addressed in 0.0.28
