### ISSUE TITLE
Add a note

### ISSUE THREAD

**Issue by supriyagoel** [open229/ruleset-model-description-schema#174]
For 100% OA systems (specifically constant volume systems), we are adding a check in the RCT to verify these systems by checking that the min OA = max OA = design supply air.
We need to add a note to thee schema, fan_system.maximum_outdoor_airflow to indicate that for a system with an economizer, the expectation is that the max OA = design supply OA

**Comment by mkarpman** [comment]
@JasonGlazer, I assume you will take care of this?

**Comment by JasonGlazer** [comment]
@mkarpman yes!

**Comment by JasonGlazer** [comment]
Add note that if minOA=maxOA=design then it is a CV DOAS. If maxOA=design only then it is an economizer.

**Comment by JasonGlazer** [comment]
Addressed in 0.0.28
