### ISSUE TITLE
Construction should have construction type

### ISSUE THREAD

**Issue by nealkruis** [open229/ruleset-model-description-schema#175]
per SCE Machine Readable Rulesets project feedback:

Many rulesets need to know the type of construction in order to determine U-factors (e.g., ECB and Title 24).

**Comment by JasonGlazer** [comment]
@nealkruis could you expand on this a bit. What would the construction types be? Are you talking about where they apply like wall, floor, roof? The Surface has a SurfaceClassificationOptions enumeration that includes that already. We also have a data element for input options like layers vs simplified.

**Comment by nealkruis** [comment]
Here is what I came up with for:

- [90.1](https://github.com/bigladder/ruleset-data-schema/blob/036558f9af8d5d32613f9123fe6629e8bf242d9e/examples/ashrae-90_1-ecb-2019.yaml#L151-L171)
- [Title 24](https://github.com/bigladder/ruleset-data-schema/blob/036558f9af8d5d32613f9123fe6629e8bf242d9e/examples/title-24-2019.yaml#L56-L74)

**Comment by JasonGlazer** [comment]
Addressed in 0.0.28
