### ISSUE TITLE
Suggested updates to OverallSimulationOutputs and new relevant data groups

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-description-schema#18]
The suggested updates to OverallSimulationOutputs and several new data elements are included in this spreadsheet: 
[https://docs.google.com/spreadsheets/d/1W1GGWOyMWdil-0Crzm23ZSsaYYp5yQGHHISHMSz4oMM/edit#gid=0](url)

In a way of background, the change is prompted by updates to the TCDs for the envelope rule that the baseline is an average of four orientations, but I included some attributes (such as is_regulated flag) that will be need for other rules.

**Comment by mkarpman** [comment]
The old link didn't work for me so I am attaching the spreadsheet with the suggested data elements here. 
[Outputs related RMR.xlsx](https://github.com/open229/ruleset-model-report-schema/files/7665282/Outputs.related.RMR.xlsx)

**Comment by JasonGlazer** [comment]
Addressed with new Output2019ASHRAE901 schema
