### ISSUE TITLE
Zone elevation

### ISSUE THREAD

**Issue by KarenWGard** [open229/ruleset-model-description-schema#182]
In order to calculate the number of floors in a building for HVAC system zone assignment, we have developed an algorithm that relies on zone elevation.

Currently in the RMI, for each building segment, there is a number given for the number of floors above and below grade, however, simply adding these numbers for all building shells may result in duplication if there are multiple building segments in the RMI.  It is common practice in eQuest, (for example), to create multiple building 'shells' to capture complex building geometry.  I believe we can anticipate that eQuest building shells will translate to building segments in the RMI.

Suggestion to the `Zone` data group, add the following data element:

`elevation` - the average elevation of the zone floor - absolute elevation above ground level (an elevation < 0 indicates that the zone is below grade)

**Comment by JasonGlazer** [comment]
@KarenWGard can you remind me why Zone:floor_name is not sufficient?

**Comment by KarenWGard** [comment]
it doesn't consistently indicate whether a floor is above or below grade

**Comment by KarenWGard** [comment]
actually, my bad.  I've been corrected.  We do not need to distinguish.
Floor Name will work.  I'll close the issue
