### ISSUE TITLE
add number_of_floors_above_grade and number_of_floors_below_grade at the building level

### ISSUE THREAD

**Issue by KarenWGard** [open229/ruleset-model-description-schema#185]
For the purpose of HVAC system selection, we request to add:

`number_of_floors_above_grade` and `number_of_floors_below_grade`

at the building level.  The note should read - "number of floors does not include any floors devoted solely to parking"

these inputs are requested to give the user additional control over the number of floors used for HVAC system selection.

**Comment by JasonGlazer** [comment]
Addressed in 0.0.29
