### ISSUE TITLE
Move data groups that are under RulesetModelInstance 

### ISSUE THREAD

**Issue by JasonGlazer** [open229/ruleset-model-description-schema#186]
Several data groups under RulesetModelInstance are there only because they are used everywhere else in the schema by a reference to an ID only. Perhaps a new data group called "DatagroupsReferencedByID" or "OnlyReferencedByID" should be added. 

This change may not be worth the effort at this point since it would have significant programming effort. What do you think @weilixu ?

**Comment by weilixu** [comment]
I agree. Currently RCT has a way to find those data groups by their ID. Adding the new data group does not change the outcome but requires a lot rework.
