### ISSUE TITLE
HeatingVentilatingAirConditioningBuildingAreaOptions2019ASHRAE901 missing an enum value

### ISSUE THREAD

**Issue by weilixu** [open229/ruleset-model-description-schema#187]
`HeatingVentilatingAirConditioningBuildingAreaOptions2019ASHRAE901` in the Enumerations2019ASHRAE901.schema.json is missing HEATED_ONLY_STORAGE type. Need to add this enum value to the schema.

Link:
https://github.com/open229/ruleset-model-description-schema/blob/main/docs229/Enumerations2019ASHRAE901.schema.json#L1068-L1076

**Comment by JasonGlazer** [comment]
Address in 0.0.29
