### ISSUE TITLE
ASHRAE229 rotation_angle field redundant?

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-description-schema#19]
I think we need to trace energy use by orientation in order to verify that the baseline is calculated as an average of four rotations. To accommodate that, I proposed adding the appropriate fields to OverallSimulationOutputs data element in a separate "issue". Having these fields would make rotation_angle field redundant, as we can just use the number of simulation output sets to track whether baseline was rotated.

**Comment by JasonGlazer** [comment]
I will make this change when #18 is finalized

**Comment by JasonGlazer** [comment]
Addressed in new Output2019ASHRAE901 schema
