### ISSUE TITLE
modify note for number_of_floors_above_grade and number_of_floors_below_grade

### ISSUE THREAD

**Issue by KarenWGard** [open229/ruleset-model-description-schema#191]
The note for number_of_floors_above_grade and number_of_floors_below_grade needs to be slightly modified so that floors that have no UNCONDITIONED zones are counted as floors.

the note currently reads:

`For the entire building including all building segments. Does not include floors devoted solely to parking.`

suggested change to:

`For the entire building including all building segments. Includes only floors that are not devoted solely to parking or unconditioned space.`

**Comment by JasonGlazer** [comment]
addressed in 0.0.30
