### ISSUE TITLE
Heat pump operating with auxilliary heat 

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-description-schema#211]
G3.1.3.1 Heat Pumps (Systems 2 and 4) states that "Electric air-source heat pumps shall be modeled with electric auxiliary heat and an outdoor air thermostat. The systems shall be controlled to energize auxiliary heat only when the outdoor air temperature is less than 40°F. The air-source heat pump shall be modeled to continue to operate while auxiliary heat is energized." 

There is HeatingSystem.h e a t p u m p _ a u x i l l i a r y _ h e a t _ t y p e and h e a t p u m p _ l o w _ s h u t o f f _ t e m p e r a t u r e schema elements, but there seems to be no way to verify the requirement in the last sentence. Suggest adding HeatingSystem.heatpump_operates_when_auxilliary_heat (true/false).

**Comment by JasonGlazer** [comment]
@mkarpman I have always assumed that when heating_system.heatpump_auxilliary_heat_high_shutoff_temperature is greater than heating_system.heatpump_low_shutoff_temperature that the range of temperatures between them both the heat pump and the auxiliary heat both operate. Does that cover the concern you raised?

**Comment by JasonGlazer** [comment]
@mkarpman Do you still want a change or should I close this issue?

**Comment by mkarpman** [comment]
I don't feel strongly about it, but I thought this requirement is conceptually similar to economizer high limit shut-off + integrated operation. So even if heat pump capacity can no longer meet the load, it keeps running in parallel with auxilliary heat if themerature is above the cut-off.

**Comment by JasonGlazer** [comment]
Clarify expected behavior in note.

**Comment by JasonGlazer** [comment]
Addressed in 0.0.37
