### ISSUE TITLE
parallel VAV fan-powered boxes run as first stage of heating

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-description-schema#212]
G3.1.3.14 Fan Power and Control (Systems 6 and 8) says that "Fans in parallel VAV fan-powered boxes shall run as the first stage of heating before the reheat coil is energized." There seems to be no schema element to check for that. Perhaps add Terminal.fan_powered_box_heat_first_stage.

**Comment by KarenWGard** [comment]
would a boolean true/false suffice for this data element?

**Comment by KarenWGard** [comment]
we suggest a better name: `is_first_stage_heat_fan_powered_box`

**Comment by JasonGlazer** [comment]
Will be in 0.0.36 schema and called it "is_fan_first_stage_heat"
