### ISSUE TITLE
Missing is_integrated element in AirEconomizer data group

### ISSUE THREAD

**Issue by JacksonJ-KC** [open229/ruleset-model-description-schema#214]
G3.1.2.6 "Integrated air economizer control shall be included in baseline HVAC Systems 3 through 8, and 11, 12, and 13 based on climate as specified in Table G3.1.2.6"

For additional context, "economizer systems shall be integrated with the mechanical cooling system and be capable of and configured to provide partial cooling even when additional mechanical cooling is required to meet the remainder of the cooling load."

There is currently no way  in the schema to specify if the airside economizer is integrated. Proposing a new boolean `is_integrated` data element in the AirEconomizer group.

**Comment by JasonGlazer** [comment]
Addressed in the 0.0.35 schema update
