### ISSUE TITLE
typo found in CoolingSystem.oversizing_factor

### ISSUE THREAD

**Issue by KarenWGard** [open229/ruleset-model-description-schema#218]
the description for the CoolingSystem.oversizing_factor reads

"The oversizing factor applied to the peak load that results in the heat capacity. Zero indicates no oversizing."

It should read: "The oversizing factor applied to the peak load that results in the **cool** capacity. Zero indicates no oversizing."

**Comment by JasonGlazer** [comment]
Thanks for noticing this. Addressed in upcoming schema 0.0.36
