### ISSUE TITLE
suggest clarification to the note for supply_air_temperature_reset_load_fraction

### ISSUE THREAD

**Issue by KarenWGard** [open229/ruleset-model-description-schema#219]
The note for **supply_air_temperature_reset_load_fraction** could use some clarification.  Currently in the RCT, this data element is used to verify supply air reset temperature control, specifically that the cooling supply air is at the setpoint at when the load is >= 50% load and that SAT is increased until it is equal to the zone temperature at 0% load.  Therefore, we suggest the following edit:

`When temperature_control is LOAD_RESET_TO_SPACE_TEMPERATURE, this is the threshold fraction below which supply air temperature reset begins.  Between the stated load fraction and 0% load the supply air temperature is ramped linearally until the supply air temperature reaches the zone. The supply air temperature is specified in Terminal.`

**Comment by JasonGlazer** [comment]
Updated in 0.0.36
