### ISSUE TITLE
Chiller part load efficiency range

### ISSUE THREAD

**Issue by weilixu** [open229/ruleset-model-description-schema#220]
The schema sets Chiller part load efficiency [range](https://github.com/open229/ruleset-model-description-schema/blob/main/docs229/ASHRAE229.schema.json#L3648) to 0-1.

If Chiller PL efficiency type is IPLV, the value could well above 1.0. Could we remove the maximum threshold?

**Comment by JasonGlazer** [comment]
I will fix that on the next schema update

**Comment by JasonGlazer** [comment]
Part of the 0.0.36 schema update.
