### ISSUE TITLE
Rename "is_autosized" to "is_sized based_design_day"

### ISSUE THREAD

**Issue by JasonGlazer** [open229/ruleset-model-description-schema#221]
90.1 does not require autosizing but simply the sizing of components with the software. Some software may not automatically put the sizes from a sizing run based on a design day into the annual simulation, but instead, this step may be manual. 

Also, look for other uses of the term autosize in the schema.

**Comment by supriyagoel** [comment]
@JasonGlazer the suggested change looks good to me

**Comment by JasonGlazer** [comment]
Addressed in schema update 0.0.36
