### ISSUE TITLE
Missing CONSTANT enum in the temperatureResetOptions

### ISSUE THREAD

**Issue by weilixu** [open229/ruleset-model-description-schema#229]
In the latest schema, the `tempeartureResetOptions` is missing a `CONSTANT` enum for [rule 22-19](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section22/Rule22-19.md).

**Comment by JasonGlazer** [comment]
@weilixu we already have an option of "NO_RESET" which I would have interpreted as the same as "CONSTANT." Do you see them as different? If so, please elaborate. If they are the same, do you think I should replace "NO_RESET" with "CONSTANT?

**Comment by JasonGlazer** [comment]
@weilixu I'm just trying to clear out some old issues. I think if that rule just used "NO_RESET" instead of "CONSTANT" we would not need to change the schema. What do you think?

**Comment by JasonGlazer** [comment]
@weilixu should I keep this issue open?
