### ISSUE TITLE
"Simplified" Method to Specify HeatRejection fan power

### ISSUE THREAD

**Issue by JacksonJ-KC** [open229/ruleset-model-description-schema#232]
`fan_electric_input_power` was removed from the HeatRejection data group in addressing the Issue below.
[https://github.com/open229/ruleset-model-description-schema/issues/181](https://github.com/open229/ruleset-model-description-schema/issues/181)

However, now there is no way to specify the full load fan power if it is known directly (no SIMPLE methods of specification like for Fan and Pump). For eQUEST there is no input associated with nameplate motor horsepower, nor brake horsepower/shaft power. Heat rejection fan power is only available as the full load input power, or as a ratio of input power to nominal heat rejection capacity.

**Comment by JasonGlazer** [comment]
@KarenWGard, since you prompted the changes in #181, would it be possible for you and @JacksonJ-KC to propose a solution that addresses all concerns?

**Comment by KarenWGard** [comment]
the data names were changed so that Heat rejection fan specification is consistent between `Fan` and `HeatRejection`.

The change from `fan_electric_input_power` to the new data elements were prompted by rule 22-17, which reads "The baseline heat rejection device shall have an efficiency of 38.2 gpm/hp"

In discussions with the group, especially Maria, we concluded that the "hp" in the equation is the `fan_shaft_power`

We could add `HeatRejection.fan_design_electric_power` to be consistent with the `Fan` data elements and nomenclature, but we would need a way to convert to `fan_shaft_power` in order to evaluate rule 22-17.

@JacksonJ-KC - thoughts on this?

**Comment by JacksonJ-KC** [comment]
`HeatRejection.fan_design_electric_power` works for me. For 22-17 use `Pfan = bhp × 746/fan motor efficiency` where fan motor efficiency = the efficiency from Table G3.9.1 for the next motor size greater than the bhp

**Comment by JacksonJ-KC** [comment]
`HeatRejection.fan_design_electric_power` would address the issue on my end. However, I disagree that the hp in 38.2 gpm/hp is referring to fan shaft power. The notes a, b, c, g in Table 6.8.1-7 all indicate that the denominator is referring to the fan motor nameplate hp. I do not see a reason to think that the units changed to shaft power for the 38.2 specification.

**Comment by JacksonJ-KC** [comment]
This would not help at all unfortunately with regards to rule 22-17... likely a step in the wrong direction if others agree that it is referring to nameplate hp. It may not be possible to evaluate in that case

**Comment by claperle** [comment]
I agree with Jackson that the hp is motor hp and not shaft power.

**Comment by KarenWGard** [comment]
Let's discuss this with the RDS workgroup next week.

**Comment by JacksonJ-KC** [comment]
@JasonGlazer Conclusion is to add back the `fan_design_electric_power` data element to HeatRejection and Karen will update rule 22-17 and check for any other rules impacted.

**Comment by JasonGlazer** [comment]
@KarenWGard and @JacksonJ-KC so what should the note read for fan_design_electric_power? For reference the fan_shaft_power notes now reads: "Power delivered to the fan’s shaft and does not include the mechanical drive losses. Equivalent to fan brake horsepower for inch-pound units." and Fan.design_elecric_power reads "Only used when specification_method is set to Simple."

**Comment by JasonGlazer** [comment]
Addressed in upcoming schema update 0.1.1
