### ISSUE TITLE
Make connection diagram more readable

### ISSUE THREAD

**Issue by JasonGlazer** [open229/ruleset-model-description-schema#234]
[ASHRAE229connection.pdf](https://github.com/open229/ruleset-model-description-schema/files/14336915/ASHRAE229connection.pdf)

**Comment by JacksonJ-KC** [comment]
@JasonGlazer I have been using miro.com to create diagrams related to the eQUEST implementation. Maybe unlikely that it could automate from the schema files but it can look legible and professional with some skill and effort. 

Whether I have that skill is up for debate, but I do my best!
