### ISSUE TITLE
Requesting PumpSpeedControlOptions `OTHER` or `TWO_SPEED`

### ISSUE THREAD

**Issue by JacksonJ-KC** [open229/ruleset-model-description-schema#235]
Corresponding to eQUEST control option: "TWO-SPEED-PUMP - The pump can operate at two speeds. The low-speed is determined by MIN-SPEED. You should choose MIN-SPEED to match the actual low speed ratio of the pump, typically 0.67 or 0.5."

**Comment by JasonGlazer** [comment]
Addressed in 0.0.37
