### ISSUE TITLE
Child Loops / Secondary Loops

### ISSUE THREAD

**Issue by JacksonJ-KC** [open229/ruleset-model-description-schema#242]
The schema makes it clear in the notes for `FluidLoop.child_loops` that secondary loops should be described as children to the primary loops they are connected to, but it is not clear if child/secondary loops should _also_ be described in `RulesetModelDescription.fluid_loops` where the note is "Contains a list of fluid loops on the site." 

My interpretation from these notes would be that child loops should be duplicated in both locations (but I know from RCT tests that they are not). Suggest clarifying `RulesetModelDescription.fluid_loops` note to exclude child loops.

**Comment by JasonGlazer** [comment]
I don't think the intent was to repeat the FluidLoop so I think we should change the wording in the notes for RulesetModelDescription.fluid_loops to say it should exclude child loop.

**Comment by JasonGlazer** [comment]
Addressed in 0.0.37 update
