### ISSUE TITLE
Clarify note for service_water_piping in ServiceWaterHeatingDistributionSystem

### ISSUE THREAD

**Issue by KarenWGard** [open229/ruleset-model-description-schema#243]
In ServiceWaterHeatingDistributionSystem, the note for service_water_piping states "Other service water piping connected to this one as children." which suggests that ServiceWaterHeatingDistributionSystem has a primary loop somewhere.  Suggest changing the language to:

"Service water piping connected to this Service Water Heating Distribution System"

**Comment by JasonGlazer** [comment]
Addressed in 0.0.37 update
