### ISSUE TITLE
confusing note for Zone.served_by_service_water_heating_system

### ISSUE THREAD

**Issue by KarenWGard** [open229/ruleset-model-description-schema#246]
The note for Zone.served_by_service_water_heating_system reads:

"Contains a single ID of the service water heating system serving the zone - from Unique Identification Number in ServiceWaterHeatingSystem. Constraint to use when implemented :ServiceWaterHeatingDistributionSystem:"

What does "Constraint to use when implemented :ServiceWaterHeatingDistributionSystem" mean?  Also, "ServiceWaterHeatingSystem" should be changed to: "ServiceWaterHeatingDistributionSystem"

**Comment by JasonGlazer** [comment]
This should be fixed to just use ServiceWaterHeatingDistributionSystem in the first sentence of the note. It may have been left over when we changed names, but I missed it.

A newer version of the schema description format uses the term "constraint" to describe when a data element can only reference a specific data group. This data element would only make sense when used with the ServiceWaterHeatingDistributionSystem data group.

**Comment by JasonGlazer** [comment]
Addressed in 0.0.37 update
