### ISSUE TITLE
ServiceWaterPiping - new data element for piping_losses

### ISSUE THREAD

**Issue by KarenWGard** [open229/ruleset-model-description-schema#247]
To evaluate the Service Water Heating section for 90.1, we need to evalaute whether the SHW is modeled with piping losses.  Suggest adding a data element:

piping_losses_modeled: true / false

**Comment by JasonGlazer** [comment]
@KarenWGard remind me, is this pumping losses (friction) or thermal losses?

**Comment by KarenWGard** [comment]
thermal losses

**Comment by JasonGlazer** [comment]
Added to 0.0.37 update
