### ISSUE TITLE
Modeled Building Altitude

### ISSUE THREAD

**Issue by JacksonJ-KC** [open229/ruleset-model-description-schema#249]
There is currently no provision for the modeled altitude to be described in the schema, and no way of knowing if the flow rates described in various data elements are those at the building altitude or if they are normalized to sea-level. Altitude can have a significant impact on the airflow rates in a model (eQUEST's help text example shows 20% increase in airflow for 5000' altitude) and could potentially be done differently between user, proposed, and baseline models accidentally, or as a means of intentionally "gaming" the results.

I would propose that `altitude` be added as a data element under `RulesetModelDescription` with `Integer` data type and that consideration go towards specifying the conditions (building altitude vs. sea-level) for flow rates listed in the schema.

**Comment by JasonGlazer** [comment]
@JacksonJ-KC, from your discussion, it seems less important to know the altitude than to know if the airflows have already been adjusted for that altitude. Maybe a boolean called something like "are_airflows_normalized_to_sea_level" would be more appropriate, what do you think? Or maybe we need both?

**Comment by JacksonJ-KC** [comment]
If airflows are not normalized to sea level then it becomes important to verify that the altitude is the same for all RMDs. My thought is that if `altitude` is not a part of the schema then all airflows should be noted that they must be the sea-level normalized airflow. If `altitude` is added to RMD then also adding the boolean you suggest makes sense to me.

**Comment by JasonGlazer** [comment]
Addressed in upcoming schema change for 0.1.0
