### ISSUE TITLE
Suggest we add number_of_floors_served data element to Elevator data table

### ISSUE THREAD

**Issue by claperle** [open229/ruleset-model-description-schema#250]
I think we need a number_of_floors_served data element added to the Elevator data table. Each elevator does not necessarily serve all floors in the building and we need to know the number of floors served for some of the elevator RDSs.

**Comment by JacksonJ-KC** [comment]
This rule is under development and relies on this new data element being added to the schema. The exact data element being used in the rule implementation is `number_of_floors_served`

**Comment by JasonGlazer** [comment]
@JacksonJ-KC are you sure we need this because Appendix G only cares about the peak motor power for the elevator which is not related to the number of floors served?

**Comment by JacksonJ-KC** [comment]
In 2019 it is needed to determine which row to use in Table G3.9.2. 

In 2022 it will have an even bigger role.

**Comment by JasonGlazer** [comment]
Addressed in schema update for 0.1.0
