### ISSUE TITLE
Suggest adding draw_pattern to ServiceWaterHeatingEquipment

### ISSUE THREAD

**Issue by KarenWGard** [open229/ruleset-model-description-schema#252]
In order to evaluate whether equipment meets the minimum efficiency requirements in Table 7.8 for Service Water Heating, we need to know the draw pattern (VERY_SMALL, LOW, MEDIUM, or HIGH).

Suggest adding draw_pattern to ServiceWaterHeatingEquipment with these options.

Thanks.

**Comment by JasonGlazer** [comment]
Addressed in 0.0.37
