### ISSUE TITLE
add BuildingSegment.service_water_heating_area_type

### ISSUE THREAD

**Issue by KarenWGard** [open229/ruleset-model-description-schema#256]
In ASHRAE 90.1, the SWH area type is required for building area types.  For consistency in the schema, please add:

BuildingSegment.service_water_heating_area_type

**Comment by JasonGlazer** [comment]
@KarenWGard are you suggesting that we do this and #255 or just one of them?

**Comment by KarenWGard** [comment]
both.  One is a name change so that it's consistent with the other building
area type tags, and one is a new data element.

**Comment by JasonGlazer** [comment]
Added in 0.0.37 update.
