### ISSUE TITLE
make ServiceWaterHeatingUse.served_by_distribution_system a required field

### ISSUE THREAD

**Issue by KarenWGard** [open229/ruleset-model-description-schema#257]
due to the `ServiceWaterheating` architecture, it is currently possible for a `Space` to have `ServiceWaterHeatingUses` that are not connected to a `ServiceWaterHeatingDistributionSystem`.  Unconnected uses mean that service water heating will not actually be modeled.  Suggest changing `ServiceWaterHeatingUse.served_by_distribution_system` field to mandatory.

**Comment by JasonGlazer** [comment]
Added to 0.0.37
