### ISSUE TITLE
ServiceWaterHeatingUse - is the flowrate intended to be mixed or only hot water

### ISSUE THREAD

**Issue by KarenWGard** [open229/ruleset-model-description-schema#260]
Check in Title24 if the SWH use is hot water only or mixed.

**Comment by JasonGlazer** [comment]
@KarenWGard did you ever find out an answer to this?

**Comment by JasonGlazer** [comment]
@KarenWGard should I keep this issue open?

**Comment by JasonGlazer** [comment]
I will add a note that is for the hot water use only.

I will also fix then note for "temperature_at_fixture" which is a copeo

**Comment by JasonGlazer** [comment]
Addressed in 0.1.2 schema update
