### ISSUE TITLE
ServiceWaterHeatingSpaceOptions2019ASHRAE901 - enumeration options not found

### ISSUE THREAD

**Issue by KarenWGard** [open229/ruleset-model-description-schema#262]
ServiceWaterHeatingSpaceOptions2019ASHRAE901 - enumeration options not found in the standard.

**Comment by JasonGlazer** [comment]
I think it is called ServiceWaterHeatingAreaOptions2019ASHRAE901 in the Enumerations2019ASHRAE901.schema.yaml file. I will update it to use the correct name.

**Comment by JacksonJ-KC** [comment]
I just came to report this and saw you were already on it! :)

**Comment by JasonGlazer** [comment]
Addressed in schema update for 0.1.0
