### ISSUE TITLE
New Data Element: `MiscellaneousEquipment.automatic_controlled_percentage`

### ISSUE THREAD

**Issue by JacksonJ-KC** [open229/ruleset-model-description-schema#265]
A new data element is needed under the MiscellaneousEquipment data group to evaluate [Rule 12-3](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section12/Rule12-3.md): `automatic_controlled_percentage`

**Comment by JasonGlazer** [comment]
Addressed in schema 0.1.0 update
