### ISSUE TITLE
New Data Element `RulesetProjectDescription.is_orientation_dictated_by_site`

### ISSUE THREAD

**Issue by JacksonJ-KC** [open229/ruleset-model-description-schema#267]
This data element is necessary to evaluate the exception: 

> 1) If it can be demonstrated to the satisfaction of the rating authority that the building orientation is dictated by site considerations.

**Comment by JacksonJ-KC** [comment]
This was a suggestion on RDS call 8/7/2024. It would be a compliance parameter - very likely entered by a user separately from the model.

It is specifically needed because a fail case must exist for all primary rules. This would allow evaluating a fail case in the rule "There are four baseline rotations (i.e., four baseline models differing in azimuth by 90 degrees and four sets of baseline model results) if vertical fenestration area per each orientation differ by more than 5%.". We can provide a certain fail if `RulesetProjectDescription.is_orientation_dictated_by_site == False` and baseline rotations do not exist. 

The rule offers value by identifying the case where baseline rotations are not needed due to vertical fenestration area being within 5% for each orientation, so it does provide value beyond saving someone from looking to see if 4 baseline models exist.

**Comment by JacksonJ-KC** [comment]
With proposed revisions to the standard language it may no longer be a requirement that every primary rule has both a PASS and a FAIL case. Accordingly, this additional data element would not be as helpful and may not be necessary.

**Comment by JasonGlazer** [comment]
I am considering closing this issue. @JacksonJ-KC do you agree?

**Comment by JacksonJ-KC** [comment]
Agreed
