### ISSUE TITLE
add RETAIL_DISPLAY to LightingPurposeOptions2019ASHRAE901 Enumerations

### ISSUE THREAD

**Issue by KarenWGard** [open229/ruleset-model-description-schema#269]
request addition of **RETAIL_DISPLAY** to the **LightingPurposeOptions2019ASHRAE901** Enumeration in support of the rule that reads:

> Where retail display lighting is included in the proposed building design in accordance with Section 9.5.2.2(b), the baseline building design retail display lighting additional power shall be equal to the limits established by Section 9.5.2.2(b) or same as proposed, whichever is less.

**Comment by JasonGlazer** [comment]
Addressed in schema 0.1.0 update
