### ISSUE TITLE
Clarify Note for FanSystem.operating_schedule

### ISSUE THREAD

**Issue by JacksonJ-KC** [open229/ruleset-model-description-schema#270]
Different modeling software may handle fractional schedules assigned to fan systems differently, or perhaps not allow them at all. The 90.1-2019 ruleset needed to make a decision on how to interpret non-binary values and implemented the convention that the fan system is only interpreted to be operational for the hour when the value is 1. 

It is important that RPD generation developers understand how fan system schedules are expected to be represented by the RCT to know if any transformations need to be made that are specific to that tool. I think that would be helpful if the schema noted for this data element that the assigned schedule should only have 1s or 0s, or had a more official way of enforcing a schedule type made of strictly binary values.

**Comment by JasonGlazer** [comment]
Update the  note to read: "If the schedule is not present, the fansystem  is always operating. Schedule values of zero when fan is scheduled to be off and one when the fan is scheduled to be on. No values beside 0 and 1 are allowed. Constraint to use when implemented :Schedule:"

Addressed in schema update 0.1.0
