### ISSUE TITLE
HeatingSystem/CoolingSystem vs. Terminal - Note Clarification

### ISSUE THREAD

**Issue by JacksonJ-KC** [open229/ruleset-model-description-schema#272]
There is some confusion currently stemming from the wording for 3 of the Terminal data element notes: 

**Current wording in question:**
"System configurations that typically are at the zone and include a compressor (such as packaged terminal air conditioning, packaged terminal heat pumps, window air conditioning units, and water loop heat pumps) should be reported in the schema using HeatingSystem and CoolingSystem. Systems that include gas or electric furnaces should be reported in the schema using HeatingSystem. **_System configurations that are at the zone and_** only include fans and coils (such as four-pipe fan coil, two-pipe fan coil, radiant systems, baseboards, and chilled beams) should be reported in the schema using Terminal with the chilled water and hot water systems described in the cooling_source and heating_source data elements (and any other relevant Terminal Data elements). Evaporative cooling systems should be described in CoolingSystem. Passive diffusers with no coil or fan should be described in Terminal."

Suggest changing this note to remove any opportunity for interpretation around what "at the zone" could mean, and have the location of a system's heating/cooling capacity (HS/CS or Terminal) be definitive and predictable.

**Suggested wording:**
"System configurations that typically are at the zone and include a compressor (such as packaged terminal air conditioning, packaged terminal heat pumps, window air conditioning units, and water loop heat pumps) should be reported in the schema using HeatingSystem and CoolingSystem. Systems that include gas or electric furnaces should be reported in the schema using HeatingSystem. **_Distributed systems where each zone is individually served by dedicated fans and/or coils_** (such as four-pipe fan coil, two-pipe fan coil, radiant systems, baseboards, chilled beams, **_and VRF indoor-units_**) should be reported in the schema using Terminal with the **_cooling and heating_** systems described in the cooling_source and heating_source data elements (and any other relevant Terminal Data elements). Evaporative cooling systems should be described in CoolingSystem. Passive diffusers with no coil or fan should be described in Terminal."

Also note my suggestion to include the VRF system in the list of examples for system types that would be described at the terminal. This is a common system type that I feel should have explicit directions in case of confusion.

**Comment by JasonGlazer** [comment]
@JacksonJ-KC This wording has been debated so much that I hate to make changes since I feel we have reached a consensus. I know you have mentioned it before, but could you remind me how the existing language is problematic?

**Comment by JacksonJ-KC** [comment]
The wording of "system configurations that are **at the zone**" implies that: a system whose fan and coils exist "outside the zone" but is ducted to only serve that one zone - does not meet the criteria to be described using Terminal cooling and heating.

**Comment by JacksonJ-KC** [comment]
The above is an issue because it causes a determining factor of the HVAC System vs Terminal to be whether the system is ducted or not. Most modeling software does not include any notion of whether a system is ducted and instead allows the effects of ductwork to be captured through static pressure or fan power adjustment. This causes the HVAC System vs Terminal question to be determined by a Compliance Parameter so the structure of an RPD file would change based on the value of this Compliance Parameter. This is an undesirable effect as we only want Compliance Parameters to populate additional data elements, not restructure data groups.

**Comment by JasonGlazer** [comment]
Addressed in 0.1.1 schema update
