### ISSUE TITLE
Suggest Allowing Humidification Systems to Exist as a Separate HeatingSystem

### ISSUE THREAD

**Issue by JacksonJ-KC** [open229/ruleset-model-description-schema#276]
Being forced to associate humidification with either the heating_system or the preheat_system is problematic. In real life, humidification is its own system component separate from any heating system. It could also be thought of as a heating system itself. 

To address this I suggest allowing a list of heating systems under the heating_ventilating_air_conditioning_system, or alternatively creating an additional data element `humidification_system` to store a HeatingSystem data group

**Comment by JacksonJ-KC** [comment]
Another idea is to move `humidification_type` up to the `heating_ventilating_air_conditioning_system`

**Comment by JasonGlazer** [comment]
The second option seems like it has a low impact, I will plan on that.

**Comment by JasonGlazer** [comment]
Addressed in schema 0.1.0 update
