### ISSUE TITLE
Boilers and Chillers Efficiencies

### ISSUE THREAD

**Issue by JacksonJ-KC** [open229/ruleset-model-description-schema#278]
Boilers and chillers should be able to contain multiple efficiency values/metrics the same way as HeatingSystem/CoolingSystem so that RPD generators do not need to conditionally populate the correct efficiency metric based on the capacity thresholds of any particular ruleset.

For example, for 90.1-2019: boilers need to populate `AFUE` if less than 300,000 Btu/h, `Et` if less than 2,500,000 Btu/h, or else `Ec`. RPD generation tools should not need to follow this logic set by 90.1-2019

**Comment by JasonGlazer** [comment]
Great suggestion and makes the handling of this in the schema more consistent. Added in 0.1.0 schema update.
