### ISSUE TITLE
Missing grocery store in the ServiceWaterHeatingAreaOptions2019ASHRAE901

### ISSUE THREAD

**Issue by weilixu** [open229/ruleset-model-description-schema#280]
Missing the Grocery Store building area type

https://github.com/open229/ruleset-model-description-schema/blob/6a13d2053d60ad3e85ad162f068ffaddd2185511/docs229/Enumerations2019ASHRAE901.schema.json#L822

**Comment by JasonGlazer** [comment]
added during schema 0.1.0 update
