### ISSUE TITLE
ServiceWaterHeatingUseUnitOptions - clarify units

### ISSUE THREAD

**Issue by KarenWGard** [open229/ruleset-model-description-schema#283]
The ServiceWaterHeatingUseUnitOptions do not specify what the actual units are.  Suggest:

POWER_PER_PERSON - `btu / hr / person`
POWER_PER_AREA - `btu / hr / ft2`
POWER - `btu / hr`
VOLUME_PER_PERSON - `gpm / person`
VOLUME_PER_AREA - `gpm / ft2`
VOLUME - `gpm`

**Comment by weilixu** [comment]
I think the schema needs to stay in metric unit system. We need to add these unit clarification in metric units.

**Comment by KarenWGard** [comment]
yes, you're right:

POWER_PER_PERSON - `Watts / person`
POWER_PER_AREA - `Watts / m2`
POWER - `Watts`
VOLUME_PER_PERSON - `Liters / minute / person`
VOLUME_PER_AREA - `Liters / minute / m2`
VOLUME - `Liters / minute`

**Comment by JasonGlazer** [comment]
Included in the schema 0.1.0 update
