### ISSUE TITLE
ServiceWaterHeatingEquipment Efficiency Metrics

### ISSUE THREAD

**Issue by KarenWGard** [open229/ruleset-model-description-schema#287]
In order to bring the ServiceWaterHeatingEquipment in line with other large HVAC equipment such as Chillers and Boilers, suggest adding a **ServiceWaterHeatingEfficiencyMetricOptions**

The new EfficiencyMetricOptions would include the following fields that are currently listed under ServiceWaterHeatingEquipment:

`THERMAL_EFFICIENCY`
`STANDBY_LOSS_FRACTION`
`UNIFORM_ENERGY_FACTOR`

We would also like to add:

`STANDBY_LOSS_ENERGY`  --  units of Watts

For conversion between STANDBY_LOSS_ENERGY (btu/hr) and STANDBY_LOSS_FRACTION, use the formula given here:

https://www.energy.ca.gov/sites/default/files/2021-11/CBECC-Res_UserManual_2019.2.0_ada.pdf 9.6.4.8

To complete the suggested change, in **ServiceWaterHeatingEquipment**, remove the fields:

`thermal_efficiency
standby_loss_fraction
uniform_energy_factor`

add these fields:

`efficiency_metric_types`
`efficiency_metric_values`

**Comment by JasonGlazer** [comment]
@KarenWGard what about regular "energy_factor", I presume that should also be part of the list and removed as an explicit field, correct?

**Comment by JasonGlazer** [comment]
Addressed in 0.1.1 schema update
