### ISSUE TITLE
Modify Schedule.hourly_heating_design_day and hourly_cooling_design_day to tke [0..8784]

### ISSUE THREAD

**Issue by claperle** [open229/ruleset-model-description-schema#295]
Many software tools including eQuest and I believe EnergyPlus as well allow the user to specify design day schedules for each day of the year. Simulations are then run across multiple days with the specified design day weather conditions held constant and with the design day schedule varying each day (in eQuest it also varies the sun angle for each day). Equipment is then sized based on the peak across the days simulated (or some varriation of this). 

Currently Schedule.hourly_cooling_design_day and Schedules.hourly_heating_design_day only allow a single [0..24 hour schedule to be entered for each. We suggest that this be changed to a [0..8784] schedule like it is for Schedule.hourly_values. 

In addition, I recommend that the schema include a note that the schedule should be populated with -1 (or some other indicator) to indicate days in which design day is not simulated. All days where the design day is simulated the actual design day schedule value would be populated in the schedule for each hour.

**Comment by JasonGlazer** [comment]
Added: 
- hourly_heating_design_year
- hourly_cooling_design_year
- design_year_ignore_indicator

This seems a bit clunky so perhaps some more refinement will be needed.

Addressed in 0.1.1 schema update.
