### ISSUE TITLE
Clarification for HeatingSystem.heatpump_low_shutoff_temperature

### ISSUE THREAD

**Issue by KarenWGard** [open229/ruleset-model-description-schema#298]
the `HeatingSystem.heatpump_low_shutoff_temperature` is used to determine whether the heat pump is allowed to operate at the same time as auxiliary heat.  ASHRAE 90.1 RCT [Rule 23-17](https://github.com/pnnl/ruleset-checking-tool/pull/1570) is currently using -56F as a cutoff temperature at or below which, heatpumps are considered to be operating continuously even when there is auxiliary heat.  -56F is the lowest recorded temperature in a habitable area of the USA in the last 10-years (Cotton, Minnesota - January 27, 2019).  There are arguments for using other temperatures:

-80F is the coldest recorded temperature in recent years in a habitable place... Yakustk, Russia - January 18, 2023
−459.67 F ... nothing colder.

The discussion about exactly what temperature the low number should be is purely academic, because no normal heat pump will have any capacity at these temperatures, but a number should be selected and communicated in the schema.

**Comment by JasonGlazer** [comment]
I am adding to the note: 

> For heat pumps with no lower temperature limit, this value should not be provided or set to -999.

This assumes that we have rules and RCT functionality that test for the presence of a data element value.

This will be included in 0.1.1

**Comment by claperle** [comment]
> I am adding to the note:
> 
> > For heat pumps with no lower temperature limit, this value should not be provided or set to -999.
> 
> This assumes that we have rules and RCT functionality that test for the presence of a data element value.
> 
> This will be included in 0.1.1

@JasonGlazer I like that more elegant solution!

**Comment by KarenWGard** [comment]
Yes. Very nice
