### ISSUE TITLE
Clarify `Terminal.minimum_outdoor_airflow` with DCV

### ISSUE THREAD

**Issue by JacksonJ-KC** [open229/ruleset-model-description-schema#300]
It is not clear what the minimum outdoor airflow should represent in zones that have demand control ventilation. 
- Should it be the design minimum (at max occupancy)? 
- Should it be the area-based/ach-based rate only (excluding occupant-based rate)?

If another data element existed `design_minimum_outdoor_airflow` it would allow a more complete representation to be provided in the data.

**Comment by JasonGlazer** [comment]
Are both the existing a proposed data elements needed for App G rules?

**Comment by JasonGlazer** [comment]
I think I will just add a note that describes this as the design minimum based on the maximum occupancy. Is that sufficient?

**Comment by JasonGlazer** [comment]
Notes added in 0.1.2 schema update
