### ISSUE TITLE
`air_distribution_effectiveness` can be different for different terminal types within the same zone

### ISSUE THREAD

**Issue by JacksonJ-KC** [open229/ruleset-model-description-schema#303]
Suggest relocating `air_distribution_effectiveness` from Zone to Terminal but having `average_air_distribution_effectiveness` at the Zone to represent the value that was used for the zone's ventilation rate procedure calculation.

**Comment by JasonGlazer** [comment]
Would keeping this at the zone level and just adding a note that it is the zone average sufficient?

**Comment by JacksonJ-KC** [comment]
I think in principle that would work but should the note be more specific to say the zone average used for VRP calc? 

Confusion could stem from effectiveness being different in heating vs cooling, and "zone average" could raise question is it design-flow-weighted-average?

**Comment by JasonGlazer** [comment]
I went back and looked at the rules and at 90.1-2019 and it is supposed to be the zone level: 

![image](https://github.com/user-attachments/assets/303a9965-e3d0-4932-9eff-af49ab2df732)


I think some notes on the source should be sufficient.

**Comment by JasonGlazer** [comment]
Addressed as part of the schema 0.1.2 update
