### ISSUE TITLE
add field "service_water_heating_design_and_control" to ServiceWaterPiping

### ISSUE THREAD

**Issue by KarenWGard** [open229/ruleset-model-description-schema#305]
In order to evaluate Service Water Heating loop flow control, we request that a field: `service_water_heating_design_and_control` with a reference to a `FluidLoopDesignAndControl` object be added to `ServiceWaterPiping`

**Comment by JasonGlazer** [comment]
@KarenWGard I added this to 0.1.2 update but please review the FluidLoopDesignAndControl and let me know which data elements are expected to be used by SWH systems and which are unlikely to be used. Also, are there any existing data elements that are no longer needed. If you find additional changes are needed, please add them to a new issue.
