### ISSUE TITLE
`RulesetModelDescription.type` = `PROPOSED` Fails Validation

### ISSUE THREAD

**Issue by JacksonJ-KC** [open229/ruleset-model-description-schema#306]
RPD files are failing validation for having `PROPOSED` as the value for type because `PROPOSED` is in both of CommonRulesetModelOptions and RulesetModelOptions2019T24Res

**Comment by JacksonJ-KC** [comment]
Suggest removing `PROPOSED` from RulesetModelOptions2019T24Res or changing `oneOf` to `anyOf`

**Comment by JacksonJ-KC** [comment]
Same issue with `USER`

**Comment by JasonGlazer** [comment]
I missed this  one and it should have been fixed as part of the fix to #263

**Comment by JasonGlazer** [comment]
Addressed in 0.1.2 schema update
