### ISSUE TITLE
suggestion - break up single yaml file

### ISSUE THREAD

**Issue by MatthewSteen** [open229/ruleset-model-description-schema#4]
Suggestion to break up the current single yaml file into multiple files similar to https://github.com/open205/schema-205/tree/master/schema-source files. I suggest breaking the data groups up by major _design discipline_, which would align it with building drawings and the [National CAD standard](https://www.nationalcadstandard.org/ncs6/content.php).

- General
- Architectural
- Electrical
- Mechanical
- Plumbing

**Comment by JasonGlazer** [comment]
Why would this be better?

**Comment by MatthewSteen** [comment]
Just a suggestion to take or leave, but I can think of two reasons.

1. The files would have fewer lines of code. The single YAML file currently has almost 1000 LOC and isn't finished, so I could see it being 10000+ when finished.
2. It would make finding objects easier because they would be categorized into separate files.

**Comment by JasonGlazer** [comment]
Given the level of connectedness of different schema portions, we decided during the September 20, 2024, Schema Working group call not to break up the schema as suggested.
