### ISSUE TITLE
Element for humidity_control_setpoint

### ISSUE THREAD

**Issue by claperle** [open229/ruleset-model-description-schema#44]
Hi All,

I am working on the following rule "Humidity Control Setpoints shall be the same for proposed design and baseline building design." and could not located a humidity control setpoint in the schema. I'd like to propose adding the following elements shjown below. However, I know different projects and software might use different humidity control variables. For example, relative humidity with a reference temperature. Not sure if we want to include multiple options. If we do, then I suppose we need a test case for all options?

FanSystem: humidity_control_max_dewpoint_setpoint
FanSystem: humidity_control_min_dewpoint_setpoint

Christina

**Comment by supriyagoel** [comment]
@claperle and @JasonGlazer i am wondering if similar to 'FluidLoopDesignandControl' we need an 'AirloopDesignandControl' which can include such parameters.

@claperle i am not sure, depends upon how many options we end up having. For anything that is same in P and B RMR, we plan to add a universal rule that just goes through a list of data elemts that are required to eb the same. So we need not develop TCDs for any rule that is verifying that P RMR = B RMR or U RMR = P RMR.

**Comment by claperle** [comment]
@supriyagoel That's right, thank you for the reminder.

**Comment by JasonGlazer** [comment]
@supriyagoel and @claperle so do we want these data elements added even though they will be the same?

**Comment by mkarpman** [comment]
I believe this discussion is about requirement in Table G3.1 "Temperature and Humidity Schedules. Temperature and
humidity control set points and schedules as well as temperature control throttling range shall be the same for proposed design and baseline building design." If so, suggest adding Zone.humidity_setpoint_schedule to support this rule.

**Comment by mkarpman** [comment]
@JasonGlazer I suggested just having Zone.humidity_setpoint_schedule up above. Why do you think we need separate heating and cooling humidity schedules?

**Comment by mkarpman** [comment]
OK, I agree. In eQUEST, there are min and max humidity inputs. So perhaps use this instead of schedule?

**Comment by JasonGlazer** [comment]
The language you pointed out in Appendix G is temperature and humidity schedules.

**Comment by mkarpman** [comment]
That's why I suggested schedules originally. Your call - I don't have strong feelings either way. Does E+ have schedules for humidity?

**Comment by JasonGlazer** [comment]
Addressed this issue in 0.0.13
