### ISSUE TITLE
Should HVACSystem object reference just one fan_system?

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-description-schema#78]
Currently, RMR allows multiple fan_systems under HeatingVentilationAirConditioningSystem data group. The note says "Normally
one fan system is used but second fan systems may be used when a direct outdoor air system is used." I think the plan it to use a different HeatingVentilationAirConditioningSystem object in this case. Suggest using a single fan_system object and not allow multiple entries.

**Comment by JasonGlazer** [comment]
Addressed in 0.0.8

**Comment by mkarpman** [comment]
No, I cannot think of a reason. Perhaps doublecheck with schema WG?
