### ISSUE TITLE
Request to add data element for integrated waterside economizer.

### ISSUE THREAD

**Issue by xingcx** [open229/ruleset-model-description-schema#82]
For Rule 22-11, "For Baseline chilled-water system that does not use purchased chilled water and does not serve System-11 with an integrated fluid economizer, variable-flow secondary pump shall be modeled as 13W/gpm at design conditions."

For this rule, we can decide if we want to add two new data elements, one for waterside economizer and one for integrated/non-integrated type. If not, we can request manual review for this rule.

But I'm not sure if the integrated fluid economizer should be associated with the chiller (it seems typically integrated fluid economizer is for chillers) or CHW loop or System-11.

**Comment by JasonGlazer** [comment]
@supriyagoel and @mkarpman I'm not sure where to indicate this in the schema either, do you have any recommendations?

**Comment by mkarpman** [comment]
1. It seems that the secondary pump power would be the same (13 W/GPM) for System 11 as for other baseline CHW systems with on-site chillers. For system 11, the additional 3W/GPM would be added to primary loop, not secondary loop. 
2. Perhaps we can treat water-side economizer as a chiller with compressor_type=water_side_economizer?

**Comment by JasonGlazer** [comment]
Addressed in 0.0.13 by adding FluidLoopDesignAndControl.has_integrated_waterside_economizer boolean.
