### ISSUE TITLE
Move HeatRejection. design_wetbulb_temperature under Weather?

### ISSUE THREAD

**Issue by xingcx** [open229/ruleset-model-description-schema#83]
For RDS rule 22-16 and 22-17, "The baseline heat rejection device shall have an approach of 25.72 – (0.24 × WB), based on design temperature rise of 10°F, valid for wet-bulbs from 55°F to 90°F. ", "The baseline condenser-water design supply temperature shall be calculated using the cooling tower approach to the 0.4% evaporation design wet-bulb temperature, valid for wet-bulbs from 55°F to 90°F."

Does it make sense to move design_wetbulb_temperature from HeatRejection to Weather as it is possible that the wet-bulb reported under heat rejection device is not correct (e.g. default values in a program, etc)?

This might also affect any rule related to Section 3.1.2.2.1, "Weather conditions used in sizing runs to determine baseline equipment capacities shall be based on design days developed using heating design temperatures, cooling design temperature, and cooling design wet-bulb temperature."

**Comment by JasonGlazer** [comment]
Unless we decide to have specific design days defined as part of the Weather data group, I don't think we should move this item. In Appendix G this is specifically the 0.4% value but the Weather references to design days that can have 0.4%, 1.0% or 2.0% and that is really the only reference in Weather to design days.
