### ISSUE TITLE
Is FanSystem.exhaust_schedule necessary?

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-description-schema#93]
FanSystem object includes {supply_fans}, {return_fans}, {exhaust_fans} and {releif_fans}. There is also FanSystem.operating_schedule object that presumably determines when all of these fans are allowed to run (0 off, 1 on). In addition, there is also FanSystem.exhaust_schedule attribute. Perhaps this field is redundant to FanSystem.operating_schedule and should be removed?

**Comment by JasonGlazer** [comment]
@mkarpman I think exhaust sometimes operates at different times than the central system such as for restaurant exhaust hoods and laboratory hoods.

**Comment by mkarpman** [comment]
@JasonGlazer should these zonal exhaust fans be captured under terminal or as a new attribute of zone?

**Comment by JasonGlazer** [comment]
I guess I presumed that is what these were, a collection of zonal exhaust fans.

**Comment by mkarpman** [comment]
I think there may be central exhaust fan at a system level plus zonal exhaust fans (e.g., bathroom, kitchen, exhaust hood, etc.).

**Comment by supriyagoel** [comment]
in the case there is a central exhaust fan, does that need a FanSystem.exhaust_schedule attribute? If yes, then we might need a check to verify that the FanSystem.exhaust_schedule = FanSystem.operating_schedule, correct?

**Comment by mkarpman** [comment]
I am not sure there needs to be a separate FanSystem.exhaust_schedule attribute. We currently have a single fan system object that may include multiple supply, return and exhaust fans that all share majority of operating parameters (e.g., operation_during)occupied, operation_during_unoccupied, fan_control, is_variabile_air_flow, etc. So why would central exhaust fan have separate schedule?

**Comment by JasonGlazer** [comment]
I removed the FanSystem.exhaust_schedule in 0.0.15 but I am still concerned that we put it in there for a reason. We also have Zone.exhaust_airflow_rate but no schedule at the zone level regarding exhaust.

**Comment by mkarpman** [comment]
Perhaps we need to add exhaust schedule at the zone level since we alread have exhaust rate there?

**Comment by JasonGlazer** [comment]
At this point, lets not worry about it until we find a requirement that needs it.

**Comment by mkarpman** [comment]
Sounds good to me.

**Comment by supriyagoel** [comment]
yup, makes sense.

**Comment by claperle** [comment]
I suggest that we add the exhaust schedule on the zone level to check via
the umbrella check that it is modeled the same in the baseline and
proposed.

*Christina LaPerle* PE, BEMP, CEM, CBCP
Senior Energy Engineer, Associate
________________
[image: image.png]
Phone 860.266.6220
We are always looking for motivated professionals to join our team. See our
career options here <https://karpmanconsulting.net/available-careers>!

**Comment by mkarpman** [comment]
I would vote for it also. Having exhaust_rate but not schedule seems incomplete.

**Comment by JasonGlazer** [comment]
Added Zone.exhaust_airflow_rate_multiplier_schedule as part of 0.0.15
