### ISSUE TITLE
Add terminal fan operation type descriptors for occupied and unoccupied hours. 

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-description-schema#96]
Exception to G3.1.2.4 requires that “For Systems 6 and 8, only the terminal-unit fan and reheat coil shall be energized to meet heating set point during unoccupied hours.” 
We currently don't have data element in the RMR to indicate terminal fan behavior. I suggest adding terminal.operation_during_occupied and terminal.operation_during_occupied with <FanSystemOperationType> enumerations to accommodate this App G requirement

**Comment by JasonGlazer** [comment]
@mkarpman this seems more like a requirement to lock out central heating during unoccupied hours than a general control strategy. If you agree, how about we add Terminal.lock_out_central_heat_during_unoccupied as a boolean? or maybe this belongs in HeatingSystem?

**Comment by mkarpman** [comment]
I like it. Perhaps it should be under FanSystem to keep company to opperation_during_unoccupied

**Comment by JasonGlazer** [comment]
Good idea!

**Comment by supriyagoel** [comment]
@JasonGlazer and @mkarpman there is also the required verified for reheat coil to be energized during unoccupied hrs if there is a heating load. would we add an explicit Boolean for this as well?

**Comment by JasonGlazer** [comment]
I think this should cover both (the title of the issue said only "fan" but the description is about "fan and reheat coil"

**Comment by supriyagoel** [comment]
ok, that makes sense

**Comment by JasonGlazer** [comment]
Addressed in 0.0.15
