### ISSUE TITLE
Heating/cooling efficiency at design vs rating conditions

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-description-schema#98]
Table G3.1 #10, proposed design column item (b) has the following requirement: Mechanical equipment efficiencies
shall be adjusted from actual design conditions to the standard rating conditions specified in Section 6.4.1 if required by the simulation model.

I don't believe we currently have a field for chillers, boilers, heatingsystem and coolingsystem to indicate whether the specified efficiencies are at design conditions or rated conditions. If so, suggest adding an attribute "EfficiencyConditions" to each applicable data object with options "Design" and "Rating"

**Comment by JasonGlazer** [comment]
we have Chiller.design_capacity and Chiller.rated_capacity, Boiler.design_capacity and Boiler.rated_capacity already. I added similar fields for rated to HeatingSystem and CoolingSystem that will be in 0.0.15

**Comment by mkarpman** [comment]
OK, that makes sense.
