### ISSUE TITLE
Efficiency with fan power extracted

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-description-schema#99]
90.1 requires modeling cooling and heating efficiency with fan power excluded for both the baseline and proposed design. To accommodate that, suggest adding COPnfheating and COPnfcooling to HeatingSystem and CoolingSystem respectively.

**Comment by JasonGlazer** [comment]
This will be in 0.0.15

**Comment by mkarpman** [comment]
Jason, when you add new attributes, do you also include the trio of fields below, with values set to "unknown"? I forgot if we discussed that. 

![image](https://user-images.githubusercontent.com/65044990/164093657-96488b06-749e-4558-960e-76a7c2a81f39.png)

**Comment by JasonGlazer** [comment]
I try to set these to unknown for new fields. Although it is possible I have missed one or two.

**Comment by mkarpman** [comment]
Thanks! I'll comb through everything again in a bit and fill in any gaps then.
